/**
 * STOCKS DATA - TEMPLATE ONLY (NO STATIC PRICES!)
 *
 * Bu dosya sadece hisse listesini ve metadata'yı içerir.
 * FİYATLAR VE DEĞİŞİMLER unified-market-data.js tarafından API'den çekilir.
 *
 * ⚠️ ASLA static fiyat ekleme! Tüm veriler API'den gelecek.
 */

window.STOCKS_DATA = {
    "us_stocks": [
        {"symbol": "AAPL", "name": "Apple Inc.", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "MSFT", "name": "Microsoft Corporation", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "GOOGL", "name": "Alphabet Inc.", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "AMZN", "name": "Amazon.com Inc.", "sector": "Consumer Cyclical", "price": 0, "change": 0},
        {"symbol": "TSLA", "name": "Tesla Inc.", "sector": "Automotive", "price": 0, "change": 0},
        {"symbol": "META", "name": "Meta Platforms Inc.", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "NVDA", "name": "NVIDIA Corporation", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "V", "name": "Visa Inc.", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Healthcare", "price": 0, "change": 0},
        {"symbol": "WMT", "name": "Walmart Inc.", "sector": "Consumer Defensive", "price": 0, "change": 0},
        {"symbol": "PG", "name": "Procter & Gamble Co.", "sector": "Consumer Defensive", "price": 0, "change": 0},
        {"symbol": "MA", "name": "Mastercard Inc.", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "HD", "name": "The Home Depot Inc.", "sector": "Consumer Cyclical", "price": 0, "change": 0},
        {"symbol": "BAC", "name": "Bank of America Corp.", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "DIS", "name": "The Walt Disney Company", "sector": "Communication Services", "price": 0, "change": 0},
        {"symbol": "NFLX", "name": "Netflix Inc.", "sector": "Communication Services", "price": 0, "change": 0},
        {"symbol": "ADBE", "name": "Adobe Inc.", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "CRM", "name": "Salesforce Inc.", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "CSCO", "name": "Cisco Systems Inc.", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "INTC", "name": "Intel Corporation", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "AMD", "name": "Advanced Micro Devices", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "PEP", "name": "PepsiCo Inc.", "sector": "Consumer Defensive", "price": 0, "change": 0},
        {"symbol": "KO", "name": "The Coca-Cola Company", "sector": "Consumer Defensive", "price": 0, "change": 0},
        {"symbol": "NKE", "name": "Nike Inc.", "sector": "Consumer Cyclical", "price": 0, "change": 0},
        {"symbol": "MRK", "name": "Merck & Co. Inc.", "sector": "Healthcare", "price": 0, "change": 0},
        {"symbol": "PFE", "name": "Pfizer Inc.", "sector": "Healthcare", "price": 0, "change": 0},
        {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Healthcare", "price": 0, "change": 0},
        {"symbol": "ORCL", "name": "Oracle Corporation", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "QCOM", "name": "QUALCOMM Inc.", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "IBM", "name": "IBM Corporation", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "TXN", "name": "Texas Instruments", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "AVGO", "name": "Broadcom Inc.", "sector": "Technology", "price": 0, "change": 0},
        {"symbol": "UNH", "name": "UnitedHealth Group", "sector": "Healthcare", "price": 0, "change": 0},
        {"symbol": "CVX", "name": "Chevron Corporation", "sector": "Energy", "price": 0, "change": 0},
        {"symbol": "XOM", "name": "Exxon Mobil Corporation", "sector": "Energy", "price": 0, "change": 0},
        {"symbol": "BA", "name": "The Boeing Company", "sector": "Industrials", "price": 0, "change": 0},
        {"symbol": "CAT", "name": "Caterpillar Inc.", "sector": "Industrials", "price": 0, "change": 0},
        {"symbol": "GE", "name": "General Electric", "sector": "Industrials", "price": 0, "change": 0},
        {"symbol": "MMM", "name": "3M Company", "sector": "Industrials", "price": 0, "change": 0},
        {"symbol": "HON", "name": "Honeywell International", "sector": "Industrials", "price": 0, "change": 0},
        {"symbol": "UPS", "name": "United Parcel Service", "sector": "Industrials", "price": 0, "change": 0},
        {"symbol": "GS", "name": "The Goldman Sachs Group", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "MS", "name": "Morgan Stanley", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "AXP", "name": "American Express Company", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "BLK", "name": "BlackRock Inc.", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "C", "name": "Citigroup Inc.", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "WFC", "name": "Wells Fargo & Company", "sector": "Financial", "price": 0, "change": 0},
        {"symbol": "T", "name": "AT&T Inc.", "sector": "Communication Services", "price": 0, "change": 0},
        {"symbol": "VZ", "name": "Verizon Communications", "sector": "Communication Services", "price": 0, "change": 0}
    ],
    "bist_stocks": [
        {"symbol": "THYAO", "name": "Türk Hava Yolları", "sector": "Ulaştırma", "price": 0, "change": 0},
        {"symbol": "GARAN", "name": "Garanti Bankası", "sector": "Finans", "price": 0, "change": 0},
        {"symbol": "AKBNK", "name": "Akbank", "sector": "Finans", "price": 0, "change": 0},
        {"symbol": "ISCTR", "name": "İş Bankası (C)", "sector": "Finans", "price": 0, "change": 0},
        {"symbol": "YKBNK", "name": "Yapı Kredi Bankası", "sector": "Finans", "price": 0, "change": 0},
        {"symbol": "HALKB", "name": "Halkbank", "sector": "Finans", "price": 0, "change": 0},
        {"symbol": "VAKBN", "name": "Vakıfbank", "sector": "Finans", "price": 0, "change": 0},
        {"symbol": "TUPRS", "name": "Tüpraş", "sector": "Enerji", "price": 0, "change": 0},
        {"symbol": "PETKM", "name": "Petkim", "sector": "Kimya", "price": 0, "change": 0},
        {"symbol": "AKSEN", "name": "Aksa Enerji", "sector": "Enerji", "price": 0, "change": 0},
        {"symbol": "AYEN", "name": "Ayen Enerji", "sector": "Enerji", "price": 0, "change": 0},
        {"symbol": "EREGL", "name": "Ereğli Demir Çelik", "sector": "Metal Eşya", "price": 0, "change": 0},
        {"symbol": "KRDMD", "name": "Kardemir (D)", "sector": "Metal Eşya", "price": 0, "change": 0},
        {"symbol": "SAHOL", "name": "Sabancı Holding", "sector": "Holding", "price": 0, "change": 0},
        {"symbol": "KCHOL", "name": "Koç Holding", "sector": "Holding", "price": 0, "change": 0},
        {"symbol": "DOHOL", "name": "Doğan Holding", "sector": "Holding", "price": 0, "change": 0},
        {"symbol": "TCELL", "name": "Turkcell", "sector": "Telekomünikasyon", "price": 0, "change": 0},
        {"symbol": "TTKOM", "name": "Türk Telekom", "sector": "Telekomünikasyon", "price": 0, "change": 0},
        {"symbol": "PGSUS", "name": "Pegasus", "sector": "Ulaştırma", "price": 0, "change": 0},
        {"symbol": "SISE", "name": "Şişe Cam", "sector": "Taş Toprak", "price": 0, "change": 0},
        {"symbol": "ASELS", "name": "Aselsan", "sector": "Teknoloji", "price": 0, "change": 0},
        {"symbol": "ARCLK", "name": "Arçelik", "sector": "Metal Eşya", "price": 0, "change": 0},
        {"symbol": "VESTL", "name": "Vestel Elektronik", "sector": "Metal Eşya", "price": 0, "change": 0},
        {"symbol": "BIMAS", "name": "BİM Mağazalar", "sector": "Perakende", "price": 0, "change": 0},
        {"symbol": "MGROS", "name": "Migros", "sector": "Perakende", "price": 0, "change": 0},
        {"symbol": "SOKM", "name": "Şok Marketler", "sector": "Perakende", "price": 0, "change": 0},
        {"symbol": "FROTO", "name": "Ford Otosan", "sector": "Metal Eşya", "price": 0, "change": 0},
        {"symbol": "TOASO", "name": "Tofaş Oto Fab.", "sector": "Metal Eşya", "price": 0, "change": 0},
        {"symbol": "ENKAI", "name": "Enka İnşaat", "sector": "İnşaat", "price": 0, "change": 0},
        {"symbol": "KOZAL", "name": "Koza Altın", "sector": "Madencilik", "price": 0, "change": 0},
        {"symbol": "IPEKE", "name": "İpek Doğal Enerji", "sector": "Enerji", "price": 0, "change": 0},
        {"symbol": "LOGO", "name": "Logo Yazılım", "sector": "Teknoloji", "price": 0, "change": 0},
        {"symbol": "TTRAK", "name": "Türk Traktör", "sector": "Metal Eşya", "price": 0, "change": 0},
        {"symbol": "ULKER", "name": "Ülker Bisküvi", "sector": "Gıda", "price": 0, "change": 0},
        {"symbol": "PRKME", "name": "Park Elektrik", "sector": "Enerji", "price": 0, "change": 0},
        {"symbol": "TAVHL", "name": "TAV Havalimanları", "sector": "Ulaştırma", "price": 0, "change": 0},
        {"symbol": "HEKTS", "name": "Hektaş", "sector": "Teknoloji", "price": 0, "change": 0},
        {"symbol": "KOZAA", "name": "Koza Anadolu Metal", "sector": "Madencilik", "price": 0, "change": 0},
        {"symbol": "EKGYO", "name": "Emlak Konut GYO", "sector": "GYO", "price": 0, "change": 0},
        {"symbol": "ISGYO", "name": "İş GYO", "sector": "GYO", "price": 0, "change": 0}
    ],
    "tefas_funds": [
        {"symbol": "AFH", "name": "Ak Portföy Hisse Senedi Fonu", "sector": "Fon - Hisse", "price": 0, "change": 0},
        {"symbol": "AKE", "name": "Ak Portföy Kısa Vadeli Tahvil Fonu", "sector": "Fon - Tahvil", "price": 0, "change": 0},
        {"symbol": "AZE", "name": "Azimut PYŞ Eurobond Fon", "sector": "Fon - Eurobond", "price": 0, "change": 0},
        {"symbol": "GAH", "name": "Garanti Portföy Hisse Senedi Fonu", "sector": "Fon - Hisse", "price": 0, "change": 0},
        {"symbol": "GEF", "name": "Garanti Portföy Eurobond Fon", "sector": "Fon - Eurobond", "price": 0, "change": 0},
        {"symbol": "GYE", "name": "Garanti Portföy Yabancı Para Fonu", "sector": "Fon - Döviz", "price": 0, "change": 0},
        {"symbol": "HFA", "name": "HSBC Portföy Hisse Senedi Fonu", "sector": "Fon - Hisse", "price": 0, "change": 0},
        {"symbol": "HYB", "name": "HSBC Portföy Yabancı Para Fonu", "sector": "Fon - Döviz", "price": 0, "change": 0},
        {"symbol": "IAH", "name": "İş Portföy Hisse Senedi Fonu", "sector": "Fon - Hisse", "price": 0, "change": 0},
        {"symbol": "IEF", "name": "İş Portföy Eurobond Fon", "sector": "Fon - Eurobond", "price": 0, "change": 0},
        {"symbol": "IPD", "name": "İş Portföy Para Piyasası Fonu", "sector": "Fon - Para Piyasası", "price": 0, "change": 0},
        {"symbol": "KYA", "name": "Kare Portföy Yabancı Para Fonu", "sector": "Fon - Döviz", "price": 0, "change": 0},
        {"symbol": "TBH", "name": "TEB Portföy Hisse Senedi Fonu", "sector": "Fon - Hisse", "price": 0, "change": 0},
        {"symbol": "TEU", "name": "TEB Portföy Eurobond Fon", "sector": "Fon - Eurobond", "price": 0, "change": 0},
        {"symbol": "YAH", "name": "Yapı Kredi Portföy Hisse Fonu", "sector": "Fon - Hisse", "price": 0, "change": 0},
        {"symbol": "YAS", "name": "Yapı Kredi Portföy Altın Fonu", "sector": "Fon - Altın", "price": 0, "change": 0},
        {"symbol": "ZPX", "name": "Ziraat Portföy BIST 30 Endeks Fonu", "sector": "Fon - Endeks", "price": 0, "change": 0},
        {"symbol": "ZRE", "name": "Ziraat Portföy Eurobond Fon", "sector": "Fon - Eurobond", "price": 0, "change": 0},
        {"symbol": "APE", "name": "Ak Portföy Petrol Para Fonu", "sector": "Fon - Emtia", "price": 0, "change": 0},
        {"symbol": "GHE", "name": "Gedik Portföy Hisse Senedi Fonu", "sector": "Fon - Hisse", "price": 0, "change": 0}
    ],
    "bes_funds": [
        {"symbol": "AAK", "name": "Anadolu Hayat Em. Agresif Değ. Gr. EYF", "sector": "BES - Agresif", "price": 0, "change": 0},
        {"symbol": "AEG", "name": "Allianz Hayat Em. Agresif Değ. Gr. EYF", "sector": "BES - Agresif", "price": 0, "change": 0},
        {"symbol": "AHD", "name": "Allianz Hayat Em. Dengeli EYF", "sector": "BES - Dengeli", "price": 0, "change": 0},
        {"symbol": "AYE", "name": "Anadolu Hayat Em. Dengeli EYF", "sector": "BES - Dengeli", "price": 0, "change": 0},
        {"symbol": "AKD", "name": "AvivaSA Em. Dengeli EYF", "sector": "BES - Dengeli", "price": 0, "change": 0},
        {"symbol": "AKH", "name": "AvivaSA Em. Hisse Senedi EYF", "sector": "BES - Hisse", "price": 0, "change": 0},
        {"symbol": "GAG", "name": "Garanti Em. Agresif Değ. Gr. EYF", "sector": "BES - Agresif", "price": 0, "change": 0},
        {"symbol": "GDN", "name": "Garanti Em. Dengeli EYF", "sector": "BES - Dengeli", "price": 0, "change": 0},
        {"symbol": "GHH", "name": "Garanti Em. Hisse Senedi EYF", "sector": "BES - Hisse", "price": 0, "change": 0},
        {"symbol": "HEM", "name": "HSBC Em. Agresif Değ. Gr. EYF", "sector": "BES - Agresif", "price": 0, "change": 0},
        {"symbol": "HDN", "name": "HSBC Em. Dengeli EYF", "sector": "BES - Dengeli", "price": 0, "change": 0},
        {"symbol": "IAG", "name": "İş Em. Agresif Değ. Gr. EYF", "sector": "BES - Agresif", "price": 0, "change": 0},
        {"symbol": "IDN", "name": "İş Em. Dengeli EYF", "sector": "BES - Dengeli", "price": 0, "change": 0},
        {"symbol": "IHE", "name": "İş Em. Hisse Senedi EYF", "sector": "BES - Hisse", "price": 0, "change": 0},
        {"symbol": "VAG", "name": "Vakıf Em. Agresif Değ. Gr. EYF", "sector": "BES - Agresif", "price": 0, "change": 0},
        {"symbol": "VDN", "name": "Vakıf Em. Dengeli EYF", "sector": "BES - Dengeli", "price": 0, "change": 0},
        {"symbol": "YAG", "name": "Yapı Kredi Em. Agresif EYF", "sector": "BES - Agresif", "price": 0, "change": 0},
        {"symbol": "YDE", "name": "Yapı Kredi Em. Dengeli EYF", "sector": "BES - Dengeli", "price": 0, "change": 0},
        {"symbol": "ZAG", "name": "Ziraat Em. Agresif Değ. Gr. EYF", "sector": "BES - Agresif", "price": 0, "change": 0},
        {"symbol": "ZDE", "name": "Ziraat Em. Dengeli EYF", "sector": "BES - Dengeli", "price": 0, "change": 0}
    ]
};

console.log('📦 Stocks Data Template yüklendi (fiyatlar API\'den gelecek)');
console.log(`📊 US Stocks: ${window.STOCKS_DATA.us_stocks.length} sembol`);
console.log(`📊 BIST Stocks: ${window.STOCKS_DATA.bist_stocks.length} sembol`);
console.log(`📊 TEFAS Funds: ${window.STOCKS_DATA.tefas_funds.length} sembol`);
console.log(`📊 BES Funds: ${window.STOCKS_DATA.bes_funds.length} sembol`);
